FROM eclipse-temurin:17-jdk

WORKDIR /app

# Copia todo el backend (incluye mvnw, .mvn y pom.xml)
COPY backend/ /app/

# Da permisos de ejecución al wrapper (por si acaso)
RUN chmod +x ./mvnw

# Descarga dependencias (sin compilar)
RUN ./mvnw dependency:go-offline

# Exponemos el puerto
EXPOSE 8080

# Ejecutamos la app en modo dev (hot reload)
CMD ["./mvnw", "spring-boot:run"]
